name: godopay-front

services:
  front:
    build: .
    container_name: godopay-front
    environment:
      VITE_USE_POLLING: "true"
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
